// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGmqFhauh1jGhym-7AS2tgzmObVeVPCAQ',
    appId: '1:50880071820:web:5aabea1a19350cf35e53a9',
    messagingSenderId: '50880071820',
    projectId: 'accioncolectiva-4c17c',
    authDomain: 'accioncolectiva-4c17c.firebaseapp.com',
    storageBucket: 'accioncolectiva-4c17c.firebasestorage.app',
    measurementId: 'G-38VRZW07Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU6pk-NLQx2HuEBGtMQ9PJ_0SkJDlpw8Y',
    appId: '1:50880071820:android:1c893b78b2528a7a5e53a9',
    messagingSenderId: '50880071820',
    projectId: 'accioncolectiva-4c17c',
    storageBucket: 'accioncolectiva-4c17c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ql1LSHMpt4pbxxepyeMcsSDzV0tfpiE',
    appId: '1:50880071820:ios:387a8661f228ca345e53a9',
    messagingSenderId: '50880071820',
    projectId: 'accioncolectiva-4c17c',
    storageBucket: 'accioncolectiva-4c17c.firebasestorage.app',
    iosBundleId: 'com.example.accioncolectiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ql1LSHMpt4pbxxepyeMcsSDzV0tfpiE',
    appId: '1:50880071820:ios:387a8661f228ca345e53a9',
    messagingSenderId: '50880071820',
    projectId: 'accioncolectiva-4c17c',
    storageBucket: 'accioncolectiva-4c17c.firebasestorage.app',
    iosBundleId: 'com.example.accioncolectiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGmqFhauh1jGhym-7AS2tgzmObVeVPCAQ',
    appId: '1:50880071820:web:65291d4c059075b25e53a9',
    messagingSenderId: '50880071820',
    projectId: 'accioncolectiva-4c17c',
    authDomain: 'accioncolectiva-4c17c.firebaseapp.com',
    storageBucket: 'accioncolectiva-4c17c.firebasestorage.app',
    measurementId: 'G-NLK24H2TLE',
  );
}
